name: Dev Branch

on:
  push:
    branches:
      - 'dev_v2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install necessary Python packages
      run: |
        pip install -r requirements.txt
    - name: Update submodules
      run: |
        git submodule update --remote

    # Parser part
    - name: Init encironment for Parser
      run: bash push_init.sh
    - name: Run Parser's main.py
      run: |
        cd data_parser
        python main.py
        cd ..

    # Generator part
    - name: Run generator's custom prechecking
      run: python prechecker.py